# Generated by Django 4.2.6 on 2023-11-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='experience_years',
            new_name='experienceYears',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='registration_no',
            new_name='registrationNo',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='language',
            field=models.CharField(max_length=100),
        ),
    ]
