# Generated by Django 4.2.6 on 2023-11-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_list', '0002_rename_experience_years_doctor_experienceyears_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('notAvailable', 'Not Available')], default='available', max_length=50),
        ),
    ]
