# Generated by Django 4.2.6 on 2023-11-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('middleName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=200)),
                ('phoneNumber', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
                ('preferredDate', models.DateField()),
                ('preferredTime', models.CharField(max_length=50)),
                ('medicalConcern', models.TextField()),
                ('address', models.TextField(max_length=300)),
            ],
        ),
    ]
