# Generated by Django 4.2.6 on 2023-11-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('waiting', 'Waiting'), ('completed', 'Completed')], default='waiting', max_length=50),
        ),
    ]
