# Generated by Django 4.2.6 on 2023-11-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_userdetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='middleName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
